version: '3'

services:
  surrealdb:
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - root
      - --pass
      - root
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./data:/data